config/routes.rb
Rails.application.routes.draw do
  resources :items

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  validates :name, presence: true

  aws_keys = if ['development', 'test'].include?(Rails.env)
    "#{Rails.root}/config/aws-keys.yml"
  else
    {
      bucket: ENV['S3_BUCKET_NAME'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    }
  end
  has_attached_file :image,
   :styles => { :medium => "300x300>", :thumb => "100x100>" },
   :default_url => "/images/:style/missing.png",
   storage: :s3,
   s3_credentials: aws_keys,
   s3_permissions: 'authenticated-read',
   path: "items/:basename.:extension",
   s3_server_side_encryption: :aes256
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def s3_url(style=nil, expires_in=30.minutes)
    image.s3_object(style).url_for(:read, secure: true, expires: expires_in).to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [
    :show,
    :edit,
    :update,
    :destroy,
  ]

  def index
    @items = Item.all
    respond_to do |format|
      format.json {render json: @items }
      format.html
    end
  end

  def show
    @item = Item.find params[:id]
    respond_to do |format|
      format.json {render json: @item }
      format.html
    end
  end

  def new
    @item = Item.new
    respond_to do |format|
      format.json {render json: @item }
      format.html
    end
  end

  def create
    @item = Item.new item_params
    @item.save
    respond_to do |format|
      format.json { render json: @item }
      format.html {redirect_to items_path}
    end
  end

  def edit
    respond_to do |format|
      format.json {render json: @item }
      format.html
    end
  end

  def update
    @item.update_attributes item_params
    respond_to do |format|
      format.json { render json: @item }
      format.html {redirect_to items_path}
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.html {redirect_to items_path}
    end
  end

private

  def set_item
    @item = Item.find params[:id]
  end

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :expected_sales_price,
      :actual_sales_price,
      :marketplace,
      :image
      )

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  = f.label :name
  = f.text_field :name 
  %br
  = f.label :description
  = f.text_field :description
  %br
  = f.label :expected_sales_price
  = f.text_field :expected_sales_price
  %br
  = f.label :actual_sales_price
  = f.text_field :actual_sales_price
  %br
  = f.label :image
  = f.file_field :image, class: 'button'
  %br
  = f.submit 'Submit'
  = link_to 'Cancel', items_path

app/views/items/edit.html.haml
Edit Item:
=render 'form'

app/views/items/index.html.haml
Items
%br
= link_to 'Return to Main', root_path
%br
= link_to 'Add New Item', new_item_path
%br
%br

%ul
  -@items.each do |item|
    %li
    = link_to item.name, item_path(item)
    = '-'
    = link_to 'Edit', edit_item_path(item)
    = '-'
    = link_to 'Delete', item_path(item), method: :delete
    %br

app/views/items/new.html.haml
Add New Item:
=render 'form'

app/views/items/show.html.haml
= link_to 'Return to Items', items_path
%br
= @item.name
%br
%br
= @item.description
%br
%br
= @item.expected_sales_price
%br
%br
= @item.actual_sales_price
%br
%br
= @item.marketplace
%br
%br
= image_tag @item.s3_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="craigslistTracker">
<head>
  <title>CraigslistItemTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='row'>
  <%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.haml
%h1 Items To Sell
= link_to 'Items Index', items_path
%div{ 'ng-view': '' }